# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# This workflow is intended to use with the release workflow also provided in this repository.
name: Publish packages

# Events that trigger this workflow
on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  publish:
    name: Publish packages to the GitHub Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 16 💿
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk

      - name: Download build environment 📥
        uses: dawidd6/action-download-artifact@v2.16.0
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: build-env
          path: ${{ github.workspace }}

      - name: Import environment ⛓
        run: cat .build-env >> $GITHUB_ENV

      - name: Install dependencies 📚
        run: chmod +x gradlew && ./gradlew

      - name: Publish packages 🗜
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_MAVEN_SUBKEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_MAVEN_SUBKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_MAVEN_SUBKEY_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
