name: reviewdog

# Events that trigger this workflow
on: [workflow_dispatch]

jobs:
  check_style:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 16 💿
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk
          cache: 'gradle'

      - name: Set up reviewdog 💿
        uses: reviewdog/action-setup@v1.0.3
        with:
          reviewdog_version: latest

      - name: Download checkstyle 📚
        run: wget -O - -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.36.2/checkstyle-8.36.2-all.jar > checkstyle.jar

      - name: Run checkstyle 📑
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: java -jar checkstyle.jar . -c .github/workflows/checkstyle.xml -f xml | reviewdog -f=checkstyle -fail-on-error=false -level=warning -reporter=github-pr-review -filter-mode=added
